### ISSUE TITLE
Fade on multiple LEDs diverges after some time

### ISSUE THREAD

**Issue by ndoo** [blogic/uledd#1]
If I set 3 LEDs (e.g. R, G, B LEDs) to fade from 0 - 255 on the same call (with the same fade on/off interval), the 3 colors' timers start to drift after a few minutes, eventually becoming somewhat random.

**Comment by blogic** [comment]
The code currently uses 1 timer per led. Change it such that there is one singular timer that upon triggering sets the new state of each LED

**Comment by ynezz** [comment]
@ndoo Should be fixed via https://github.com/blogic/uledd/pull/6 can you test/confirm? Thanks!
